version: "3"
services:

  proxy:
    image: nginx:1.13.5-alpine
    depends_on:
      - nginx
    volumes:
      - ./.docker/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/proxy/proxy_params:/etc/nginx/proxy_params

  nginx:
    image: nginx:1.13.5-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/data/nginx:/var/lib/cache/nginx
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: exozet/php-fpm:7.3-sudo
    env_file:
      - ./.docker/common.env
      - ./.env
    volumes:
      - ./:/usr/src/app:cached
    ports:
      - "9000"

  php-cli:
    image: exozet/php-fpm:7.3-sudo
    user: www-data
    entrypoint: bash
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/cache/composer:/composer/cache/
    env_file:
      - ./.docker/common.env
      - ./.env
    depends_on:
      - proxy